policy_type: 'behavior'
learnable: False
onpolicy: False
model_path: ''
model_type: 'agent'
results_folder_path: ''
obs_type: 'no_obs'
ego_action_dim: 3

train_episode: 2000

save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100
