policy_type: 'expert'
learnable: False
model_path: ''
model_type: 'agent'
results_folder_path: ''
obs_type: 'ego_state'

train_episode: 2000
eval_in_train_freq: 1
save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100
