policy_type: 'ppo'
learnable: True
model_path: 'safebench/agent/model_ckpt/ppo'
model_type: 'agent'
results_folder_path: ''
obs_type: 'simple_state'

# parameters for agent policy
ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

train_episode: 500
dims: [64, 64]

save_freq: 20
buffer_capacity: 2500

clip_epsilon: 0.2
gamma: 0.99
train_repeat_times: 4
train_interval: 4
policy_lr: 2.0e-4
value_lr: 2.0e-4
batch_size: 256
lambda_gae_adv: 0.98
lambda_entropy: 0.01
