policy_type: 'rc_sac'
learnable: True
onpolicy: False
model_path: 'safebench/agent/model_ckpt/rc_sac'
model_type: 'agent'
results_folder_path: ''
obs_type: 'simple_state'

# parameters for agent policy
ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0


train_episode: 500

save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
constrain_threshold: 1.5  # meters
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 32
min_Val: 1.0e-7
