policy_type: 'rc_sac'
learnable: True
model_path: 'safebench/agent/model_ckpt/rc_sac'
model_id: 0
results_folder_path: ''
obs_type: 'simple_state'

train_episode: 2000
eval_in_train_freq: 1
save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
constrain_threshold: 1.5  # meters
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 32
min_Val: 1.0e-7
