policy_type: 'sac'
learnable: True
model_path: 'safebench/agent/model_ckpt/sac'
model_type: 'agent'
results_folder_path: ''
obs_type: 'plant'

# parameters for agent policy
ego_action_dim: 2
ego_state_dim: 512  # obs_type: 'simple_state' -> state dim=4; obs_type: 'plant' -> state dim=512
ego_action_limit: 1.0

train_episode: 2000
eval_in_train_freq: 1
save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 32
min_Val: 1.0e-7
