policy_type: 'sac'
learnable: True
onpolicy: False
model_path: 'safebench/agent/model_ckpt/sac'
model_type: 'agent'
results_folder_path: ''
obs_type: 'ego_obs'

# parameters for agent policy
ego_action_dim: 3
ego_state_dim: 18  # 3 vehicle * 6 dimensions state
ego_state_shape: [3, 6]
ego_action_limit: 1.0

train_episode: 500

save_freq: 20
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 32
min_Val: 1.0e-7
