policy_type: 'td3'
learnable: True
model_path: 'safebench/agent/model_ckpt/td3'
model_type: 'agent'
results_folder_path: ''
obs_type: 'simple_state'

# parameters for agent policy
ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0


train_episode: 2000
eval_in_train_freq: 1
save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

hidden_size: 256

lr: 3.0e-4
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 32
update_interval: 2
action_lim: 1
target_noise: 0.2
target_noise_clip: 0.5
explore_noise: 0.1
