scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'safebench_scenario_10x.json'
scenario_category: 'planning'
policy_type: 'nf'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 2
route_id: null

# for REINFORCE policy model
model_path: 'safebench/scenario/scenario_data/model_ckpt/nf'
model_id: 1
buffer_capacity: 100
batch_size: 32
lr: 0.001
eval_in_train_freq: 10
save_freq: 10
train_episode: 1000
