scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'random.json'
scenario_category: 'planning'
policy_type: 'random'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: null
route_id: null

model_path: ''
save_freq: 40
