scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'carla_scenario_9_10x.json'
policy_type: 'sac'
learnable: True

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 9  # default null -> save and load an "all" model for all scenarios, 9 -> save and load one model for the "9" scenario
route_id: null

# for scenario id 8
scenario_state_dim: 15 # 3*5 - actor number * actor info dim
scenario_state_shape: [3, 5]
scenario_action_dim: 2

# for SAC policy model
model_path: 'safebench/scenario/scenario_data/model_ckpt/sac'
model_type: 'bv'
train_episode: 500  # the training episode for each town
save_freq: 20

buffer_capacity: 10000
buffer_start_training: 200
lr: 3.0e-4
tau: 0.005
update_iteration: 3
gamma: 0.99
batch_size: 64
min_Val: 1.0e-7
