scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'scenic.json'  # TODO: don't have the scenic.json file
scenario_category: 'scenic'
policy_type: 'scenic'

scenic_dir: 'safebench/scenario/scenario_data/scenic_data/Carla_Challenge'
scenario_id: null
route_id: null

sample_num: 20
select_num: 5

# not useful
model_path: ''
standard_action: False
buffer_capacity: 100
eval_in_train_freq: 10
save_freq: 10
train_episode: 100
