scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'standard.json'
scenario_category: 'planning'
policy_type: 'standard'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: null
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

# not useful
model_path: ''
standard_action: False
buffer_capacity: 100
eval_in_train_freq: 10
save_freq: 10
train_episode: 100
