scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'carla_scenario_9_1x.json'  # default 'safebench_scenario_1x.json' only include the route scenario in the safebench light map
policy_type: 'standard'
learnable: False

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 9
route_id: null

# not useful
model_path: ''
standard_action: False
buffer_capacity: 100

save_freq: 5
train_episode: 100
gamma: 0.99