
type: "HJR"
data_path: 'safebench/feasibility/data'
model_path: 'safebench/feasibility/model_ckpt'
scenario_id: 9

min_dis_threshold: 0.1
M: 40  # if min_dis_threshold == 0.5, then M == 10; if min_dis_threshold == 0.1, then M == 18

obs_type: "ego_obs"  # "ego_infos" contains ego and the meaningful surrounding vehicle information
feasibility_state_dim: 18  # (3 vehicle) * 6 dimensions state
state_shape: [3, 6]
agent_action_dim: 3
dims: [64, 64]

results_folder_path: ''
acc_range: [-3.0, 3.0]
steer_range: [-0.3, 0.3]


train_episode: 2000000
save_freq: 100000
buffer_capacity: 100000

gamma: 0.98
tau: 5.0e-3
expectile: 0.9

lr: 3.0e-4
batch_size: 1024