min_dis_threshold: 0.0
type: "HJR"
model_path: 'safebench/feasibility/model_ckpt'

obs_type: "ego_obs"  # "ego_infos" contains ego and the meaningful surrounding vehicle information
feasibility_state_dim: 18  # 3*6 actor_number * dim
state_shape: [3, 6]
dims: [64, 64]

results_folder_path: ''
acc_range: [-3.0, 3.0]
steer_range: [-0.3, 0.3]


train_episode: 500
save_freq: 20
buffer_capacity: 2048
train_repeat_times: 4
gamma: 0.98
tau: 5.0e-3

lr: 3.0e-4
batch_size: 256