min_dis_threshold: 0.5
type: "HJR"
model_path: 'safebench/safety_network/model_ckpt'

obs_type: "ego_info"  # "ego_infos" contains ego and the meaningful surrounding vehicle information
state_dim: 15  # 3*5 actor_number * dim
state_shape: [3, 5]
action_dim: 2

results_folder_path: ''
acc_range: [-3.0, 3.0]
steer_range: [-0.3, 0.3]


train_episode: 300
save_freq: 20
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
train_iteration: 10
train_interval: 5
batch_size: 64