min_dis_threshold: 0.5
type: "HJR"
model_path: 'safebench/safety_network/model_ckpt'

#obs_type: "plant"  # the "plant" contains encoded state from plant
#state_dim: 512  # the hidden size of the plant encoder
#action_dim: 2

obs_type: "ego_info"  # "ego_infos" contains ego and the meaningful surrounding vehicle information
state_dim: 15  # 3*5 actor_number * dim
state_shape: [3, 5]
action_dim: 2

results_folder_path: ''
acc_range: [-3.0, 3.0]
steer_range: [-0.3, 0.3]


train_episode: 240
eval_in_train_freq: 1
save_freq: 20
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
tau: 0.005
train_iteration: 10
gamma: 0.99
batch_size: 64

pretrained_model_path: 'safebench/agent/model_ckpt/PlanT_state_encoder/checkpoints/state_encoder.ckpt'

training:
  max_NextRouteBBs: 2 # max 10 prevents really high ids if route is long


network:
  hf_checkpoint: "safebench/agent/model_ckpt/PlanT_state_encoder/checkpoints/bert-medium"
  embd_pdrop: 0.1