min_dis_threshold: 0.5
type: "HJR"
model_path: 'safebench/safety_network/model_ckpt/HJR'
model_id: 2
obs_type: "PlanT"
results_folder_path: ''
acc_range: [-3.0, 3.0]
steer_range: [-0.3, 0.3]
ego_state_dim: 8
ego_action_dim: 2

train_episode: 2000
eval_in_train_freq: 1
save_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

lr: 5.0e-4
tau: 0.005
train_iteration: 10
gamma: 0.99
batch_size: 64
