policy_type: 'ppo'
learnable: True
onpolicy: True
model_path: 'frea/agent/model_ckpt/ppo'
model_type: 'agent'
results_folder_path: ''
obs_type: 'ego_obs'

# parameters for agent policy
ego_action_dim: 3
ego_state_dim: 24  # (3 vehicle + 1 route) * 6 dimensions state
ego_state_shape: [4, 6]
ego_action_limit: 1.0

train_episode: 2000
dims: [256, 256]

save_freq: 20
buffer_capacity: 2048

clip_epsilon: 0.2
gamma: 0.99
train_repeat_times: 4

policy_lr: 2.0e-4
value_lr: 2.0e-4
batch_size: 256
lambda_gae_adv: 0.98
lambda_entropy: 0.01
